### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by linostar** [linostar/zombireBot#1]
- [x] Implements round end, player clear, and highscore register
- [x] reword bonus texts to add more diversity
- [x] implement authentication totally via nickserv 
- [x] voice registered users (via channel access), and change config.yml accordingly
- [x] add the rest of admin commands: stats, topscores (with dates), ...
- [x] add the rest of user commands: !howtoplay (gives link), !topscores, !defend (?), ...
- [x] add the flood control module that controls all bot msgs and notices
- [x] complete the "how to play" section in README
- [x] copy the "how to play" section to a separate page on linostar.github.io
- [x] check whether players stats are properly saved when pymysql reconnects after timing out
- [x] add !vampires and !zombies listing user commands
- [x] add cut_to_chunks() for breaking long strings (if needed)
